### ISSUE TITLE
When I use body in mailto on the command line, the compose screen does not open.

### ISSUE THREAD

**Issue by over-the-stardust** [nakkag/nPOP#1]
When I open the mail compose screen by specifying mailto on the command line, nPOP exits after a few seconds if there is a body.

This means that the sample
```
  nPOP.exe mailto:hoge@hoge.hoge?Subject=test&Body=こんにちは
```
is not possible.

As far as I can tell from the source code, the initialization of TCHAR *body; in line 1708 of the URLToMailItem function in util.c is missing.
As a result, it seems to crash at mem_free(&*buf); in the URLHeadToItem function.

**Comment by nakkag** [comment]
@over-the-stardust 
Thank you for reporting.
I fixed it.
