### ISSUE TITLE
フォントサイズと高DPI設定について

### ISSUE THREAD

**Issue by pklion** [nakkag/nPOP#2]
普段からnPOPを使わせていただいている者です。

設定上でメールリストと件名の部分のフォントサイズを同じに設定しても、実際は違うサイズとして表示されてしまい、それを防ぐために普段は[高DPIスケール設定](https://anykey.bz/win/win10-dpi-high/)を利用しています。
もし可能でしたら、この設定をマニフェストにデフォルトで追加していただけませんでしょうか。
https://www.inasoft.org/talk/h202104a.html

また付随して、nPOP 1.2.5を利用したところダイアログ内のフォントサイズが変更され見切れる部分がさらに増えたように感じています。
もし追加していただけるようでしたら、個人的には要素の幅・サイズを広げていただける(か、フォントサイズを1.2.4の頃のサイズに戻していただける)と幸いです。

↓ nPOP 1.2.4
![image](https://github.com/nakkag/nPOP/assets/78145811/5f3c3e59-e4de-4d0a-b3e5-135e35c0ec55)

↓ nPOP 1.2.5
![image](https://github.com/nakkag/nPOP/assets/78145811/bad78fad-c26d-478a-97b5-0b423624b875)

↓ フォント設定
```
FontName="IBM Plex Sans JP"
FontSize=11
FontWeight=0
FontItalic=0
FontCharset=128
LvFontName="IBM Plex Sans JP"
LvFontSize=11
LvFontWeight=0
LvFontItalic=0
LvFontCharset=128
```

(nPOP バージョン 1.2.5、Windows 11)

**Comment by nakkag** [comment]
もう少し各コントロールの大きさに余裕を持たせてみます。
1.2.4の問題はフォントだけ大きくなってコントロールが追従していなかったことです。そのため前に戻す選択はないためコントロールの大きさでの対応になるかなと考えています。

**Comment by nakkag** [comment]
本文のフォントとリストのフォントを同じにしても別のサイズになるのは設定値の扱いが異なっていたためでした。
こちらは修正済です。

高DPIで拡大している場合にダイアログが大きくなってしまう件についてはフォントの拡大率の計算方法を改善して正しい大きさのダイアログで表示されるようになっています。

> 設定上でメールリストと件名の部分のフォントサイズを同じに設定しても、実際は違うサイズとして表示されてしまい、そ れを防ぐために普段は[高DPIスケール設定](https://anykey.bz/win/win10-dpi-high/)を利用しています。
> もし可能でしたら、この設定をマニフェストにデフォルトで追加していただけませんでしょうか。
> https://www.inasoft.org/talk/h202104a.html

こちらの設定は高DPIに対応していないアプリケーションに入れる設定ですが、nPOPは高DPIに対応しているためこの設定はいれません。
今回リリースしたv1.2.6で上記設定を解除しても正しく動作すると思います。

**Comment by pklion** [comment]
ありがとうございました。
